hassanhabib/Taarafo.Core

- Taarafo.Core/Controllers/PostsController.cs
- Taarafo.Core/Startup.cs
> CONTROLLERS: GET All Posts

- Taarafo.Core/Controllers/PostsController.cs
- Taarafo.Core/Taarafo.Core.csproj
> CONTROLLERS: Delete Post by Id

- Taarafo.Core/Brokers/Storages/IStorageBroker.Comments.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Comments.cs
> BROKERS: Insert Comment

- Taarafo.Core/Brokers/Storages/IStorageBroker.Comments.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Comments.cs
> BROKERS: Select All Comments

- Taarafo.Core/Brokers/Storages/IStorageBroker.Comments.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Comments.cs
> BROKERS: Select Comment By Id

- Taarafo.Core/Brokers/Storages/IStorageBroker.Comments.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Comments.cs
> BROKERS:  Update Comment

- Taarafo.Core/Brokers/Storages/IStorageBroker.Comments.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Comments.cs
> BROKERS: Delete Comment

- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.cs
- Taarafo.Core/Brokers/Storages/IStorageBroker.Comments.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Comments.cs
- Taarafo.Core/Models/Comments/Comment.cs
- Taarafo.Core/Models/Comments/Exceptions/AlreadyExistsCommentException.cs
- Taarafo.Core/Models/Comments/Exceptions/CommentDependencyException.cs
- Taarafo.Core/Models/Comments/Exceptions/CommentDependencyValidationException.cs
- Taarafo.Core/Models/Comments/Exceptions/CommentServiceException.cs
- Taarafo.Core/Models/Comments/Exceptions/CommentValidationException.cs
- Taarafo.Core/Models/Comments/Exceptions/FailedCommentServiceException.cs
- Taarafo.Core/Models/Comments/Exceptions/FailedCommentStorageException.cs
- Taarafo.Core/Models/Comments/Exceptions/InvalidCommentException.cs
- Taarafo.Core/Models/Comments/Exceptions/NullCommentException.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Exceptions.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Validations.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.cs
- Taarafo.Core/Services/Foundations/Comments/ICommentService.cs
> FOUNDATIONS: Add Comment

- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.RetrieveById.cs
- Taarafo.Core/Models/Comments/Exceptions/NotFoundCommentException.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Exceptions.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Validations.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.cs
- Taarafo.Core/Services/Foundations/Comments/ICommentService.cs
> FOUNDATIONS: Retrieve Comment By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.cs
- Taarafo.Core/Models/Comments/Exceptions/CommentServiceException.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Exceptions.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.cs
- Taarafo.Core/Services/Foundations/Comments/ICommentService.cs
> FOUNDATIONS: Retrieve All Comments

- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validation.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.cs
- Taarafo.Core/Models/Comments/Exceptions/LockedCommentException.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Exceptions.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.Validations.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.cs
- Taarafo.Core/Services/Foundations/Comments/ICommentService.cs
> FOUNDATIONS: Modify Comment

- Taarafo.Core/Migrations/20211111212024_ExtendCommentModel.Designer.cs
- Taarafo.Core/Migrations/20211111212024_ExtendCommentModel.cs
> DATA: Add Created & Updated Dates to Comment

- README.md
> DOCUMENTATION: Update The Readme of The Project

- .editorconfig
> CONFIG: Addition of solution level .editorconfig

- Taarafo.Core.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Posts/PostsApiTests.cs
- Taarafo.Core.Tests.Acceptance/Brokers/ApiBroker.Posts.cs
- Taarafo.Core.Tests.Acceptance/Models/Posts/Post.cs
- Taarafo.Core.Tests.Acceptance/Taarafo.Core.Tests.Acceptance.csproj
> ACCEPTANCE: POST Post

- Taarafo.Core.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Posts/PostsApiTests.cs
- Taarafo.Core.Tests.Acceptance/Brokers/ApiBroker.Posts.cs
> ACCEPTANCE: GET ALL Posts

- Taarafo.Core/Controllers/CommentsController.cs
- Taarafo.Core/Startup.cs
Closes #75
**201 - Created**
**400 - Bad Request**
**424 - Failed Dependency**
**409 - Conflict**
> CONTROLLERS: POST Comment

- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Logic.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.RemoveById.cs
- Taarafo.Core/Services/Foundations/Comments/CommentService.cs
- Taarafo.Core/Services/Foundations/Comments/ICommentService.cs
> FOUNDATIONS: Remove Comment By Id

- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/CloudBroker.Plans.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/CloudBroker.ResourceGroups.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/CloudBroker.Storages.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/CloudBroker.WebApps.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/CloudBroker.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.Plans.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.ResourceGroup.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.Storages.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.WebApps.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Clouds/ICloudBroker.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Configurations/ConfigurationBroker.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Configurations/IConfigurationBroker.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Loggings/ILoggingBroker.cs
- Taarafo.Core.Infrastructure.Provision/Brokers/Loggings/LoggingBroker.cs
- Taarafo.Core.Infrastructure.Provision/Models/Configurations/CloudAction.cs
- Taarafo.Core.Infrastructure.Provision/Models/Configurations/CloudManagementConfiguration.cs
- Taarafo.Core.Infrastructure.Provision/Models/Storages/SqlDatabase.cs
- Taarafo.Core.Infrastructure.Provision/Models/Storages/SqlDatabaseAccess.cs
- Taarafo.Core.Infrastructure.Provision/Program.cs
- Taarafo.Core.Infrastructure.Provision/Services/Foundations/CloudManagements/CloudManagementService.cs
- Taarafo.Core.Infrastructure.Provision/Services/Foundations/CloudManagements/ICloudManagementService.cs
- Taarafo.Core.Infrastructure.Provision/Services/Processings/CloudManagementProcessingService.cs
- Taarafo.Core.Infrastructure.Provision/Services/Processings/ICloudManagementProcessingService.cs
- Taarafo.Core.Infrastructure.Provision/Taarafo.Core.Infrastructure.Provision.csproj
- Taarafo.Core.Infrastructure.Provision/appSetttings.json
- Taarafo.Core.sln
> PROVISION: Azure Resources Provisioning

- Taarafo.Core/Controllers/CommentsController.cs
> CONTROLLERS: GET All Comments

- Taarafo.Core/Controllers/CommentsController.cs
> CONTROLLERS: GET Comment By Id

- Taarafo.Core/Controllers/PostsController.cs
> CONTROLLERS: PUT Post

- Taarafo.Core.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs
> ACCEPTANCE: DELETE Post By Id

- Taarafo.Core/Controllers/CommentsController.cs
> CONTROLLERS: PUT Comment

- Taarafo.Core.Tests.Acceptance/Models/Posts/Post.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validation.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.Add.cs
- Taarafo.Core/Migrations/20211202101002_UpdatePostModel.Designer.cs
- Taarafo.Core/Migrations/20211202101002_UpdatePostModel.cs
- Taarafo.Core/Models/Posts/Post.cs
Create
Retrieve
RetrieveAll
Update
Delete
> CODE RUB: Post and PostView Author property to string

- Taarafo.Core/Controllers/CommentsController.cs
> CONTROLLERS: DELETE Comment By Id

- Taarafo.Core.Tests.Acceptance/Apis/Comments/CommentsApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Comments/CommentsApiTests.cs
- Taarafo.Core.Tests.Acceptance/Brokers/ApiBroker.Comments.cs
- Taarafo.Core.Tests.Acceptance/Models/Comments/Comment.cs
- Taarafo.Core.Tests.Acceptance/Taarafo.Core.Tests.Acceptance.csproj
> ACCEPTANCE: Get All Comments

- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validation.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.Validations.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Posts/PostServiceTests.cs
- Taarafo.Core/Services/Foundations/Posts/PostService.Exceptions.cs
> CODE RUB: Update Same Exception As in Post Tests

- Taarafo.Core.Tests.Acceptance/Brokers/ApiBroker.Comments.cs
> BROKERS: PUT Comment

- Taarafo.Core.Tests.Acceptance/Brokers/ApiBroker.Posts.cs
> BROKERS: PUT Post

- Taarafo.Core.Tests.Acceptance/Apis/Comments/CommentsApiTests.Logic.cs
> ACCEPTANCE: Get Comment By Id

- Taarafo.Core.Tests.Acceptance/Apis/Comments/CommentsApiTests.Logic.cs
> ACCEPTANCE: Delete Comment By Id

- Taarafo.Core.Tests.Acceptance/Apis/Posts/PostsApiTests.Logic.cs
> ACCEPTANCE: GET Post By Id

- Taarafo.Core.Tests.Acceptance/Apis/Comments/CommentsApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Comments/CommentsApiTests.cs
> ACCEPTANCE: PUT Comment

- Taarafo.Core/Brokers/Storages/IStorageBroker.Profiles.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Profiles.cs
@hassanhabib could you review this PR, please?
> BROKERS: Select All Profiles

- Taarafo.Core/Controllers/ProfilesController.cs
- Taarafo.Core/Startup.cs
**Created 201:**
**Bad Request 400:**
**Conflict 409**
> CONTROLLERS: Post Profile

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupPosts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.References.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
- Taarafo.Core/Migrations/20220401024818_AddGroupPostModel.Designer.cs
- Taarafo.Core/Migrations/20220401024818_AddGroupPostModel.cs
- Taarafo.Core/Models/GroupPosts/GroupPost.cs
- Taarafo.Core/Models/Groups/Group.cs
- Taarafo.Core/Models/Posts/Post.cs
> DATA: Implement Model & Migrations for GroupPost

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostImpressions.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.cs
> Brokers: Update Post Impressions

- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
- Taarafo.Core/Migrations/20220715211302_AddEventModel.Designer.cs
- Taarafo.Core/Migrations/20220715211302_AddEventModel.cs
- Taarafo.Core/Models/Events/Event.cs
Code changes to add a new model named 'Event' to the Tarafo platform.
Also included are a new Storage Broker, which going forward will be associated with storage operations for Events in Taarafo. Entity Framework Migrations have also been setup for the same
> DATA: Event Models & Migrations

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostImpressions.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.cs
> BROKERS: Select All Post Impressions

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostImpressions.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.cs
> BROKERS: Delete Post Impression

- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validation.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Comments/CommentServiceTests.Validations.RetrieveById.cs
> CODE RUB: Update unit Tests for Comment

- Taarafo.Core/Brokers/Storages/IStorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
- Taarafo.Core/Models/Events/Event.cs
> BROKERS: Select All Events

- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.Configurations.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> CODE RUB: Refactor StorageBroker.PostImpressions.References.cs

- Taarafo.Core/Services/Foundations/Comments/ICommentService.cs
> CODE RUB: Solved mistake in methods parameter naming.

- Taarafo.Core/Migrations/20220910032910_UpdateEventModel.Designer.cs
- Taarafo.Core/Migrations/20220910032910_UpdateEventModel.cs
- Taarafo.Core/Models/Events/Event.cs
> CODE RUB: Changed Property Name And Created Migration

- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Validations.Add.cs
- Taarafo.Core/Services/Foundations/Groups/GroupService.cs
- Taarafo.Core/Services/Foundations/Groups/IGroupService.cs
> CODE RUB:Foundations Group CreateGroupAsync Changed TO AddGroupAsync

- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.Configurations.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.Configurations.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> CODE RUB: Refactor StorageBroker.GroupPost.References.cs

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostImpressions.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.cs
> BROKERS: Select Post Impression By Ids

- Taarafo.Core/Brokers/Storages/IStorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
> BROKERS: Select Event By Id

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupPosts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.cs
> BROKERS: Insert Group Post

- Taarafo.Core.Infrastructure.Build/Services/ScriptGenerationService.cs
- Taarafo.Core.Infrastructure.Provision/Taarafo.Core.Infrastructure.Provision.csproj
- Taarafo.Core.Tests.Acceptance/Taarafo.Core.Tests.Acceptance.csproj
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Validations.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Profiles/ProfileServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Profiles/ProfileServiceTests.Validations.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Profiles/ProfileServiceTests.Validations.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Profiles/ProfileServiceTests.cs
- Taarafo.Core.Tests.Unit/Taarafo.Core.Tests.Unit.csproj
- Taarafo.Core/Taarafo.Core.csproj
Hi Chris,
Please merge this asap so that we can continue with the latest packages.
@cjdutoit
> CONFIG: Update Packages

- Taarafo.Core/Brokers/Storages/StorageBroker.Profiles.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> CODE RUB: Upgrade SelectProfileByIdAsync

- Taarafo.Core/Brokers/Storages/StorageBroker.Posts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> CODE RUB: Upgrade InsertPostAsync()

- Taarafo.Core/Migrations/20221113064458_UpdateProfileWithAvatar.Designer.cs
- Taarafo.Core/Migrations/20221113064458_UpdateProfileWithAvatar.cs
- Taarafo.Core/Models/Profiles/Profile.cs
> CODE RUB: Add Profile Picture

- Taarafo.Core/Brokers/Storages/StorageBroker.PostReports.cs
- Taarafo.Core/Migrations/20221115081202_AddPostReportModel.Designer.cs
- Taarafo.Core/Migrations/20221115081202_AddPostReportModel.cs
- Taarafo.Core/Models/PostReports/PostReport.cs
> DATA: Add PostReport Model

- Taarafo.Core/Brokers/Storages/IStorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> BROKERS: Update Event

- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
> CODE RUB: Upgrade InsertEventAsync

- Taarafo.Core/Brokers/Storages/IStorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> BROKERS: Delete Event

- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> CODE RUB: Upgrade SelectAllEvents

- Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
> CODE RUB: Upgrade SelectEventByIdAsync

- Taarafo.Core/Brokers/Storages/StorageBroker.Profiles.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.cs
> CODE RUB: Upgrade InsertProfileAsync

- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Logic.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.cs
- Taarafo.Core/Services/Foundations/PostImpressions/IPostImpressionService.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.Exceptions.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.Validations.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.cs
> FOUNDATIONS: Retrieve All Post Impressions 

- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Validations.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.Validations.cs
> FOUNDATIONS: Add Post Impression

- Taarafo.Core/Brokers/Storages/StorageBroker.Groups.cs
> CODE RUB: Update StorageBroker.Groups.cs

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostImpressions.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostImpressions.cs
> CODE RUB: Update StorageBroker.PostImpressions.cs

- Taarafo.Core/Brokers/Storages/StorageBroker.Posts.cs
> CODE RUB: Update StorageBroker.Posts.cs

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupPosts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.cs
> BROKERS: Select All Group Posts

- Taarafo.Core/Controllers/ProfilesController.cs
> EXPOSERS: GET All Profiles

- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.cs
> CODE RUB: Update StorageBroker.GroupPosts.cs

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupPosts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.cs
> BROKERS: Update Group Posts

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupPosts.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupPosts.cs
> BROKERS: Select Group Post By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Logic.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.cs
- Taarafo.Core/Services/Foundations/GroupPosts/GroupPostService.Exceptions.cs
- Taarafo.Core/Services/Foundations/GroupPosts/GroupPostService.cs
- Taarafo.Core/Services/Foundations/GroupPosts/IGroupPostService.cs
> FOUNDATIONS: Retrieve All Group Posts

- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Validations.Modify.cs
- Taarafo.Core/Services/Foundations/Groups/GroupService.cs
- Taarafo.Core/Services/Foundations/Groups/IGroupService.cs
> CODE RUB: Rename Method

- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.cs
> CODE RUB: Remove unused items GroupPostServiceTests.cs

- Taarafo.Core/Controllers/GrouPostsController.cs
- Taarafo.Core/Controllers/GroupPostsController.cs
- Taarafo.Core/Startup.cs
> EXPOSERS: Post Group Post

- Taarafo.Core/Controllers/GroupPostsController.cs
> EXPOSERS: Delete Group Post

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupMemberships.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupMemberships.cs
> BROKERS: Select GroupMembership By Id

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupMemberships.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupMemberships.cs
> BROKERS: Update GroupMembership

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostReports.cs
> BROKERS: Update Post Report

- Taarafo.Core/Controllers/GroupPostsController.cs
> EXPOSERS: Get All Group Posts

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupMemberships.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupMemberships.cs
> BROKERS: Select All GroupMemberships

- Taarafo.Core/Brokers/Storages/IStorageBroker.GroupMemberships.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.GroupMemberships.cs
> BROKERS: Delete GroupMembership

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostReports.cs
- Taarafo.Core/Brokers/Storages/StorageBroker.PostReports.cs
> BROKERS: Select Post Report By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Exceptions.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Logic.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Validations.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.cs
- Taarafo.Core/Models/PostImpressions/Exceptions/InvalidPostImpressionException.cs
- Taarafo.Core/Models/PostImpressions/Exceptions/LockedPostImpressionException.cs
- Taarafo.Core/Models/PostImpressions/Exceptions/NotFoundPostImpressionException.cs
- Taarafo.Core/Services/Foundations/PostImpressions/IPostImpressionService.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.Exceptions.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.Validations.cs
- Taarafo.Core/Services/Foundations/PostImpressions/PostImpressionService.cs
> FOUNDATIONS: Remove Post Impression 

- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Logic.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.cs
- Taarafo.Core/Services/Foundations/GroupPosts/GroupPostService.Validations.cs
- Taarafo.Core/Services/Foundations/GroupPosts/GroupPostService.cs
- Taarafo.Core/Services/Foundations/GroupPosts/IGroupPostService.cs
> FOUNDATIONS: Retrieve Group Post By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTestsExceptions.RemovebyId.cs
- Taarafo.Core/Models/Groups/Exceptions/GroupDependencyValidationException.cs
- Taarafo.Core/Services/Foundations/Groups/GroupService.Exceptions.cs
> CODE RUB: Update GroupService.Exceptions methods to follow new CreateAndLogDependencyValidationException implementations

- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostImpressionProcessingServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostImpressionProcessingServiceTests.Logic.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostimpressionProcessingServiceTests.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/FailedPostImpressionProcessingServiceException.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/PostImpressionProcessingDependencyException.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/PostImpressionProcessingServiceException.cs
- Taarafo.Core/Services/Processings/PostImpressions/IPostImpressionProcessingService.cs
- Taarafo.Core/Services/Processings/PostImpressions/PostImpressionProcessingService.Exceptions.cs
- Taarafo.Core/Services/Processings/PostImpressions/PostImpressionProcessingService.cs
> PROCESSINGS: RetrieveAllPostImpressions

- Taarafo.Core/Controllers/GroupsController.cs
> EXPOSERS: Post Group

- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Logic.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Validations.Add.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Validations.Modify.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Validations.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Validations.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTestsExceptions.RemovebyId.cs
> CODE RUB: Update SameExceptionAs for GroupService Unit Tests

- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Logic.RemoveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostImpressions/PostImpressionServiceTests.Validations.RetrieveById.cs
> CODE RUB: Update PostImpressionService Unit Tests

- Taarafo.Core/Controllers/ProfilesController.cs
> CONTROLLERS:  GET Profile By Id

- Taarafo.Core/Controllers/ProfilesController.cs
> CONTROLLERS: Delete Profile By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.Exceptions.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.Logic.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.cs
- Taarafo.Core/Models/Events/Exceptions/EventDependencyException.cs
- Taarafo.Core/Models/Events/Exceptions/EventException.cs
- Taarafo.Core/Models/Events/Exceptions/EventServiceException.cs
- Taarafo.Core/Models/Events/Exceptions/EventValidationException.cs
- Taarafo.Core/Models/Events/Exceptions/EventdencyValidationException.cs
- Taarafo.Core/Models/Events/Exceptions/FailedEventServiceException.cs
- Taarafo.Core/Models/Events/Exceptions/FailedEventStorageException.cs
- Taarafo.Core/Models/Events/Exceptions/InvalidEventException.cs
- Taarafo.Core/Models/Events/Exceptions/InvalidEventReferenceException.cs
- Taarafo.Core/Models/Events/Exceptions/LockedEventException.cs
- Taarafo.Core/Models/Events/Exceptions/NotFoundEventException.cs
- Taarafo.Core/Models/Events/Exceptions/NullEventException.cs
- Taarafo.Core/Services/Foundations/Events/EventService.Exceptions.cs
- Taarafo.Core/Services/Foundations/Events/EventService.Validations.cs
- Taarafo.Core/Services/Foundations/Events/EventService.cs
- Taarafo.Core/Services/Foundations/Events/IEventService.cs
> FOUNDATIONS: Retrieve All Events

- Taarafo.Core/Controllers/GroupsController.cs
> CONTROLLERS: Get All Groups

- Taarafo.Core/Brokers/Storages/IStorageBroker.PostReports.cs
> CODE RUB: Rename Interface

- Taarafo.Core/Controllers/GroupsController.cs
> EXPOSERS: Get Group By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/PostReports/PostReportServiceTests.Exception.RetrieveAll.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostReports/PostReportServiceTests.Logic.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostReports/PostReportServiceTests.cs
- Taarafo.Core/Models/PostReports/Exceptions/FailedPostPeportServiceException.cs
- Taarafo.Core/Models/PostReports/Exceptions/FailedPostPeportStorageException.cs
- Taarafo.Core/Models/PostReports/Exceptions/FailedPostReportServiceException.cs
- Taarafo.Core/Models/PostReports/Exceptions/PostReportDependencyException.cs
- Taarafo.Core/Models/PostReports/Exceptions/PostReportServiceException.cs
- Taarafo.Core/Services/Foundations/PostReports/IPostReportService.cs
- Taarafo.Core/Services/Foundations/PostReports/PostReportService.Validations.cs
- Taarafo.Core/Services/Foundations/PostReports/PostReportService.cs
> FOUNDATIONS: Retrieve All PostReports

- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.cs
> ACCEPTANCE: GET Profile By Id

- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.cs
- Taarafo.Core.Tests.Acceptance/Brokers/ApiBroker.Profiles.cs
> ACCEPTANCE: PUT Profile

- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.Logic.cs
- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.cs
> ACCEPTANCE: DELETE Profile By Id

- Taarafo.Core.Tests.Unit/Services/Foundations/PostReports/PostReportServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostReports/PostReportServiceTests.Logic.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/PostReports/PostReportServiceTests.Validations.RetrieveById.cs
- Taarafo.Core/Models/PostReports/Exceptions/NotFoundPostReportException.cs
- Taarafo.Core/Services/Foundations/PostReports/IPostReportService.cs
- Taarafo.Core/Services/Foundations/PostReports/PostReportService.Exceptions.cs
- Taarafo.Core/Services/Foundations/PostReports/PostReportService.Validations.cs
- Taarafo.Core/Services/Foundations/PostReports/PostReportService.cs
> FOUNDATIONS: Retrieve PostReport By Id

- Taarafo.Core.Tests.Acceptance/Apis/Profiles/ProfilesApiTests.Logic.cs
> CODE RUB : Add Fact Method

- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostImpressionProcessingServiceTests.Exception.Upsert.cs
- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostImpressionProcessingServiceTests.Logic.cs
- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostImpressionProcessingServiceTests.Validation.Upsert.cs
- Taarafo.Core.Tests.Unit/Services/Processings/PostImpressions/PostimpressionProcessingServiceTests.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/InvalidPostImpressionProcessingException.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/NullPostImpressionProcessingException.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/PostImpressionProcessingDependencyValidationException.cs
- Taarafo.Core/Models/Processings/PostImpressions/Exceptions/PostImpressionProcessingValidationException.cs
- Taarafo.Core/Services/Processings/PostImpressions/IPostImpressionProcessingService.cs
- Taarafo.Core/Services/Processings/PostImpressions/PostImpressionProcessingService.Exceptions.cs
- Taarafo.Core/Services/Processings/PostImpressions/PostImpressionProcessingService.Validation.cs
- Taarafo.Core/Services/Processings/PostImpressions/PostImpressionProcessingService.cs
> PROCESSINGS: UpsertPostImpressionAsync

- Taarafo.Core/Controllers/PostImpressionsController.cs
- Taarafo.Core/Startup.cs
> CONTROLLERS: Delete Post Impressions

- Taarafo.Core/Controllers/GroupsController.cs
> CONTROLLERS: Delete Group

- Taarafo.Core.Tests.Unit/Taarafo.Core.Tests.Unit.csproj
> CONFIG: Switch to CleanMoq

- Taarafo.Core/Controllers/GroupsController.cs
> CODE RUB : RemoveGroupByIdAsync Change To RetrieveGroupByIdAsync 

- Taarafo.Core.Tests.Unit/Services/Foundations/GroupMemberships/GroupMembershipServiceTests.Exceptions.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupMemberships/GroupMembershipServiceTests.Logic.RetrieveById.cs
- Taarafo.Core.Tests.Unit/Services/Foundations/GroupMemberships/GroupMembershipServiceTests.Validations.RetrieveById.cs
- Taarafo.Core/Models/GroupMemberships/Exceptions/NotFoundGroupMembershipException.cs
- Taarafo.Core/Services/Foundations/GroupMemberships/GroupMembershipService.Exceptions.cs
- Taarafo.Core/Services/Foundations/GroupMemberships/GroupMembershipService.Validations.cs
- Taarafo.Core/Services/Foundations/GroupMemberships/GroupMembershipService.cs
- Taarafo.Core/Services/Foundations/GroupMemberships/IGroupMembershipService.cs
> FOUNDATIONS: Retrieve GroupMembership By Id
